config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  devise_for :users ,controllers: {   registrations: 'users/registrations',
    sessions: 'users/sessions' }
  resources :users ,only: [:index,:show,:edit,:update,:destroy]
  resources :skills do
    resource :user_skills, only: [:create, :destroy]
  end
  get '/mypage' => 'users#mypage'
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :user_skills
    has_many :users, through: :user_skills
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :validatable
    has_many :user_skills, dependent: :destroy
    has_many :skills, through: :user_skills
    accepts_nested_attributes_for :user_skills, allow_destroy: true
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
    belongs_to :user  
    belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController 

    def index
        @skill= Skill.all
    end
    
    def new 
        @skill = Skill.new
    end

    def create
        Skill.create!(skill_parmas)
    end

    private
    def skill_parmas
        params.require(:skill).permit(:skill_name,:skill_level,:user_id)
    end
    
end

app/controllers/user_skills_controller.rb
class User_skillsController < ApplicationController
    def create
        current_user.user_skills.create!(skill_id: params[:skill_id])
        @user_skill.save
        redirect_to root_path
    end

    def update
        @user_skill = @user.user_skills.find(parmas[:user_skill_id])
        @user_skill.save
        @user_skill.update(user_skill_params)
    end

    private
    def user_skill_params
        params.require(:user_skills).permit(:skill_level,:user_id,:skill_id)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]


  def after_sign_up_path_for(resource)
    mypage_path
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user,only: [:show,:edit,:update]
    before_action :authenticate_user!


    def index
        @user = User.all 
    end

    def new
        @user = User.new
        @skill = Skill.new
    end

    def create
        @user = User.create(user_params)
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
        unless @user == current_user
        redirect_to user_path(@user)
        end
    end

    def destroy 
        user = User.find(params[:id])
        user.destroy
        redirect_to root_url
    end

    def update
        @user = User.find(params[:id])  
        @user.update!(user_params)  
        if current_user.update(user_params)
            redirect_to user_path(current_user)
        else
            redirect_to edit_user_path(current_user)
        end
    end

    def mypage
        redirect_to user_path(current_user)
    end

    private 
        def user_params
            params.fetch(:user,{}).permit(:name, :age ,:description,:status,:twitter ,{ skill_ids: [] })
        end

            def set_user
                @user = User.find(params[:id])
            end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
    <div class="header">
    <h1>スキル把握アプリ</h1>
        <div class="header-nav">
            <% if user_signed_in? %>
                <div class="header-nav-list"><%= link_to 'マイページ', mypage_path %></div>
                <div class="header-nav-list"><%= link_to 'ユーザー一覧', users_path %></div>
                <div class="header-nav-list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></div>
            <% else %>
                <div class="header-nav-list"><%= link_to 'ログイン', new_user_session_path %></div>
                <div class="header-nav-list"><%= link_to '新規登録', new_user_registration_path %></div>
            <% end %>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>メンバー情報共有アプリ</title>
    <meta name="description" content="コミュニティ内でメンバーのスキルの把握ができずに困っていませんか？それを解決できるアプリです。持っているスキル、現在の忙しさの具合、TwitterのIDなどメンバーそれぞれの情報を管理します。">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# link_to "新規登録", new_user_session_path %>
    <div class="header">
      <%= render "layouts/navbar" %>
    </div>
    <div class="main">
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="footer-copyright">
        Copyright © 2020 Chibariyooh All Right Reserved.
      </div>
    </footer>
  </body>
</html>

app/views/skills/create.html.erb
<%# <h1>Skills#create</h1>
<p>Find me in app/views/skills/create.html.erb</p> %>
<h1 class="create-title">登録完了！</h1>
<div class="create-btn">
    <%= link_to "登録画面へ戻る", edit_user_path(current_user) %>
</div>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<%# <h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p> %>
<h1 class="add-skilltag-title">タグの追加</h1>
<div class="add-skilltag-wrapper">
    <%= form_for @skill do |k| %>
        <div>
            <%= k.label :skill_name,"追加したいスキルのタイトル" %>
            <%= k.text_field :skill_name %>
        </div>
        <div class="add-skilltag-btn">
            <%= k.submit "スキル追加"%>
        </div>
    <% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>
<h1>登録完了！</h1>
<%= link_to "一覧画面へ戻る", users_path %>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

<h1>削除完了</h1>
<%= link_to "一覧画面へ戻る", users_path %>

app/views/users/edit.html.erb
<%# <h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p> %>

<h1 class="edit-user-data-title">登録情報編集</h1>
<div class="edit-user-data-personal-wrapper">
<%= form_for @user do |f| %>
    <p>
        <%= f.label :name,"お名前" %>
        <%= f.text_field :name %>
    </p>
    <%# <p>
        <%= f.label :age, "ご年齢" %>
        <%# <%= f.text_field :age %>
    <%# </p> %> 
    <p>
        <%= f.label :description,"ご挨拶" %>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :status,"忙しさ度" %>
        <%# <%= f.text_field :status %> 
        <%= f.select :status, [["空いてます！", "空いてます！"], ["少し空いてます！", "少し空いてます！"], ["少し忙しいです！", "少し忙しいです！"], ["だいぶ忙しいです！", "だいぶ忙しいです！"]], include_blank: "選択して下さい" %>
    </p>
    <p>
        <%= f.label :twitter,"TwitterのID(@以下)" %><br>
        @<%= f.text_field :twitter %>
    </p>
</div>
<div class="edit-user-skill-data">
    <h3 class="edit-user-skill-data-title">所持スキル</h3>
    <div class="check_box edit-user-skill-data-checkbox" >
        <%= f.collection_check_boxes(:skill_ids, Skill.all, :id, :skill_name) do |b| %>
            <%= b.label { b.check_box + b.text } %>
            <br>
        <% end %>
    </div>
    <p class="add-skill-tag"><%= link_to "スキルタグの追加",new_skill_path %></p>
    <div class="update-user-data-btn">
        <%= f.submit "ユーザー情報の更新"%>
    </div>
    <p>編集ボタンが反応しない時はページをリロードしてください</p>
<% end %>
</div>

app/views/users/index.html.erb
<%# <h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p> %>
<div class="user">
    <% @user.each do |user| %>
        <div class="user-personal">
            <p class="user-personal-data">
                <span class="user-personal-data-bold">(名前)  </span><%= user.name %><br><br>
                <span class="user-personal-data-bold">(忙しさ)  </span><%= user.status %><br><br>
                <span class="user-personal-data-bold">(挨拶)<br></span><%= user.description %><br>
            </p>
            <p class="personal-url">
                <%= link_to '詳細はこちら！', user_path(user) %>
            </p>
            <p class="twitter-url">
                <%= link_to "Twitterはこちら！", "https://twitter.com/#{user.twitter}" %>
            </p>

            <% user.skills.each do |skill| %>
            <p class="user-personal-skill-name"><%= skill[:skill_name] %></p>
            <!--<p><%= skill[:skill_level] %></p>-->
            <% end %>
            <%# link_to "編集", edit_user_path(user) %>
            <%# link_to "削除", user_path(user), method: :delete, data: {confirm: "削除しますか?"} %>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<h1>新規登録</h1>
<%= form_for @user do |f| %>
    <p>
        <%= f.label :name,"お名前" %>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :age, "ご年齢" %>
        <%= f.text_field :age %>
    </p>
    <p>
        <%= f.label :description,"ご挨拶" %>
        <%= f.text_field :description %>
    </p>


    <div class="check_box" >
        <%= f.collection_check_boxes(:skill_ids, Skill.all, :id, :skill_name) do |b| %>
            <%= b.label { b.check_box + b.text } %>

            <%# !--skill_levelの表示方法が不明 %>
            <%# form_for @user_skill do |d| %>
            <%# end %>

            <br>
        <% end %>
    </div>
    <p><%= link_to "タグの追加",new_skill_path %></p>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<%# <h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p> %>

<% if user_signed_in? && @user == current_user %>
    <%# <h1>マイページ</h1> %>
    <div class="mypage-user-personal">
        <h3>基本情報</h3>
        <p class="mypage-user-personal-data">
            <span>(名前)</span><%= @user.name %><br>
            <span>(忙しさ)</span><%= @user.status %><br>
            <span>(挨拶)<br></span><%= @user.description %><br>
        </p>
        <h3>所持スキル</h3>
        <% @user.skills.each do |skill| %>
        <p class="mypage-user-personal-skill-name"><%= skill[:skill_name] %></p>
        <% end %>
        <p class="twitter-url-show">
        <%= link_to "Twitterはこちら！",  "https://twitter.com/#{@user.twitter}" %>
        </p>
    </div>
    <div class="mypage-user-edit">
        <div class="mypage-user-edit-item"><%=link_to "プロフィール情報編集", edit_user_path(current_user) %></div>
        <div class="mypage-user-edit-item"><%= link_to "ログイン情報編集", edit_user_registration_path(current_user) %></div>
        <div class="mypage-user-edit-item"><%= link_to "登録データ削除", users_path, method: :delete, data: {confirm: "削除しますか?"} %></div>
    </div>
<% else %>
    <%# <h1>ユーザーページ</h1> %>
    <div class="mypage-user-personal">
        <h3>基本情報</h3>
        <p class="mypage-user-personal-data">
            <span>名前： </span><%= @user.name %><br>
            <span>年齢：</span><%= @user.age %><br>
            <span>挨拶：</span><%= @user.description %>
        </p>
        <h3>所持スキル</h3>
        <% @user.skills.each do |skill| %>
        <p class="mypage-user-personal-skill-name"><%= skill[:skill_name] %></p>
        <% end %>
    </div>
<% end %>

<h1><%= @user.username %></h1>

<% if user_signed_in? && @user == current_user %>
    <% link_to "プロフィール編集", edit_user_registration_path(current_user) %>
<% else %>
<% end %>